import { useCallback, useEffect, useState } from 'react';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { ArrowLeft, Bookmark } from 'lucide-react-native';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ScreenContainer } from '../../components/screen-container';
import { useAuth } from '../../contexts/auth';
import { recordLearningProgress } from '../../lib/progress';
import { AudioButton, FavoriteButton, PrimaryButton, StateCard } from '../../components/ui';
import { colors, radius } from '../../constants/theme';
import type { VocabularyItem } from '../../data/types';
import { getPublishedVocabularyDetail } from '../../lib/vocabulary';

export default function VocabularyDetailScreen() {
  const router = useRouter(); const { user } = useAuth();
  const { id } = useLocalSearchParams<{ id: string }>();
  const [item, setItem] = useState<VocabularyItem | null>(null);
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading');
  const loadItem = useCallback(async () => { if (!id) return; setStatus('loading'); try { setItem(await getPublishedVocabularyDetail(id)); setStatus('ready'); } catch { setItem(null); setStatus('error'); } }, [id]);
  useEffect(() => { void loadItem(); }, [loadItem]); useEffect(() => { if (item && user) void recordLearningProgress(user.id, 'vocabulary', item.id); }, [item, user]);
  return <ScreenContainer><Pressable onPress={() => router.back()} style={styles.back}><ArrowLeft size={18} color={colors.ink} /><Text style={styles.backText}>ဝေါဟာရစာရင်းသို့</Text></Pressable>{status === 'loading' ? <StateCard kind="loading" title="စကားလုံးကို ဖွင့်နေပါတယ်" message="Published content ကို ဖတ်နေပါတယ်။" /> : status === 'error' || !item ? <StateCard kind="error" title="စကားလုံးကို မတွေ့ပါ" message="ဒီ content က မထုတ်ဝေရသေးတာ သို့မဟုတ် connection ပြဿနာ ဖြစ်နိုင်ပါတယ်။" action="ပြန်စမ်းမယ်" onAction={() => { void loadItem(); }} /> : <><View style={styles.hero}><Text style={styles.level}>HSK {item.hskLevel} · {item.partOfSpeechMy}</Text><Text style={styles.hanzi}>{item.hanzi}</Text><Text style={styles.pinyin}>{item.pinyinMarked}</Text><View style={styles.actions}><AudioButton label="အသံဖွင့်မယ်" onPress={() => undefined} /><FavoriteButton active={false} onPress={() => undefined} /></View></View><View style={styles.meaningCard}><Text style={styles.label}>မြန်မာအဓိပ္ပာယ်</Text><Text style={styles.meaningMy}>{item.meaningMy}</Text><Text style={styles.meaningEn}>{item.meaningEn}</Text>{item.category ? <Text style={styles.category}>Category · {item.category}</Text> : null}</View>{item.example ? <View style={styles.exampleCard}><Text style={styles.label}>ဥပမာ / EXAMPLE</Text><Text style={styles.exampleZh}>{item.example.sentenceZh}</Text><Text style={styles.examplePinyin}>{item.example.sentencePinyin}</Text><Text style={styles.exampleMy}>{item.example.translationMy}</Text></View> : <View style={styles.emptyExample}><Text style={styles.emptyTitle}>ဥပမာဝါကျ မထည့်ရသေးပါ</Text><Text style={styles.emptyText}>ဒီ published content မှာ example မပါသေးပါ။</Text></View>}<View style={styles.note}><Bookmark size={16} color={colors.gold} /><Text style={styles.noteText}>ဒီစကားလုံးကို နားလည်အောင် အနည်းဆုံး ၂ ကြိမ် ပြန်ဖတ်ကြည့်ပါ။</Text></View><PrimaryButton label="ဝေါဟာရစာရင်းသို့ ပြန်မယ်" onPress={() => router.back()} /></>}</ScreenContainer>;
}

const styles = StyleSheet.create({ back: { flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 24 }, backText: { color: colors.ink, fontSize: 12, fontWeight: '600' }, hero: { alignItems: 'center', paddingVertical: 28, backgroundColor: colors.primarySoft, borderRadius: radius.lg }, level: { color: colors.primary, fontSize: 10, fontWeight: '700' }, hanzi: { color: colors.ink, fontSize: 58, fontFamily: 'serif', fontWeight: '700', marginTop: 16 }, pinyin: { color: colors.primary, fontSize: 17, fontWeight: '600', marginTop: 5 }, actions: { flexDirection: 'row', alignItems: 'center', gap: 9, marginTop: 20 }, meaningCard: { padding: 19, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.surface, marginTop: 18 }, label: { color: colors.accent, fontSize: 9, letterSpacing: 1, fontWeight: '700' }, meaningMy: { color: colors.ink, fontSize: 19, fontWeight: '800', marginTop: 11 }, meaningEn: { color: colors.muted, fontSize: 12, marginTop: 4 }, category: { color: colors.primary, fontSize: 10, marginTop: 11, fontWeight: '700' }, exampleCard: { padding: 19, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.surface, marginTop: 12 }, exampleZh: { color: colors.ink, fontSize: 20, fontFamily: 'serif', fontWeight: '700', marginTop: 14 }, examplePinyin: { color: colors.primary, fontSize: 12, marginTop: 6 }, exampleMy: { color: colors.muted, fontSize: 12, lineHeight: 20, marginTop: 6 }, emptyExample: { padding: 19, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.surface, marginTop: 12 }, emptyTitle: { color: colors.ink, fontSize: 14, fontWeight: '800' }, emptyText: { color: colors.muted, fontSize: 11, marginTop: 6 }, note: { flexDirection: 'row', gap: 8, padding: 14, marginVertical: 17, borderRadius: radius.sm, backgroundColor: colors.goldSoft }, noteText: { color: '#85632A', fontSize: 10, lineHeight: 17, flex: 1 }, });
