import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import type { Session, User } from '@supabase/supabase-js';
import { supabase, supabaseConfigured } from '../lib/supabase';

type AuthContextValue = { session: Session | null; user: User | null; loading: boolean; configured: boolean; signIn: (email: string, password: string) => Promise<string | null>; signUp: (email: string, password: string, displayName: string) => Promise<string | null>; signOut: () => Promise<string | null> };
const AuthContext = createContext<AuthContextValue | undefined>(undefined);
function authError(error: unknown) { const message = error instanceof Error ? error.message.toLowerCase() : ''; if (message.includes('invalid login')) return 'Email သို့မဟုတ် password မှားနေပါတယ်။'; if (message.includes('already registered')) return 'ဒီ email နဲ့ အကောင့်ရှိပြီးသားပါ။'; if (message.includes('password')) return 'Password က အနည်းဆုံး ၆ လုံးရှိရပါမယ်။'; if (message.includes('email')) return 'Email format ကို စစ်ပေးပါ။'; return 'အကောင့်လုပ်ဆောင်ချက် မအောင်မြင်ပါ။ ခဏနေရင် ပြန်စမ်းပါ။'; }
export function AuthProvider({ children }: { children: ReactNode }) { const [session, setSession] = useState<Session | null>(null); const [loading, setLoading] = useState(true); useEffect(() => { if (!supabaseConfigured) { setLoading(false); return; } let mounted = true; void supabase.auth.getSession().then(({ data }) => { if (mounted) { setSession(data.session); setLoading(false); } }).catch(() => { if (mounted) setLoading(false); }); const { data: listener } = supabase.auth.onAuthStateChange((_event, nextSession) => { setSession(nextSession); setLoading(false); }); return () => { mounted = false; listener.subscription.unsubscribe(); }; }, []); const value = useMemo<AuthContextValue>(() => ({ session, user: session?.user ?? null, loading, configured: supabaseConfigured, signIn: async (email, password) => { if (!supabaseConfigured) return 'Supabase ကို အရင် configure လုပ်ပေးပါ။'; const { error } = await supabase.auth.signInWithPassword({ email: email.trim(), password }); return error ? authError(error) : null; }, signUp: async (email, password, displayName) => { if (!supabaseConfigured) return 'Supabase ကို အရင် configure လုပ်ပေးပါ။'; const { error } = await supabase.auth.signUp({ email: email.trim(), password, options: { data: { display_name: displayName.trim() } } }); return error ? authError(error) : null; }, signOut: async () => { if (!supabaseConfigured) return null; const { error } = await supabase.auth.signOut(); return error ? authError(error) : null; } }), [session, loading]); return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>; }
export function useAuth() { const context = useContext(AuthContext); if (!context) throw new Error('useAuth must be used inside AuthProvider'); return context; }
