import { useState } from 'react';
import { useRouter } from 'expo-router';
import { ArrowLeft, LogIn } from 'lucide-react-native';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { ScreenContainer } from '../components/screen-container';
import { PrimaryButton, StateCard } from '../components/ui';
import { colors, radius } from '../constants/theme';
import { useAuth } from '../contexts/auth';

export default function LoginScreen() { const router = useRouter(); const { signIn, loading: authLoading, configured } = useAuth(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const submit = async () => { setError(null); if (!email.trim() || !password) { setError('Email နဲ့ password ဖြည့်ပေးပါ။'); return; } setBusy(true); const result = await signIn(email, password); setBusy(false); if (result) setError(result); else router.replace('/profile'); }; return <ScreenContainer><Pressable onPress={() => router.back()} style={styles.back}><ArrowLeft size={18} color={colors.ink} /><Text style={styles.backText}>ပြန်မယ်</Text></Pressable><View style={styles.hero}><View style={styles.icon}><LogIn size={22} color={colors.primary} /></View><Text style={styles.title}>အကောင့်ဝင်မယ်</Text><Text style={styles.subtitle}>Shine Chinese နဲ့ ဆက်လက်လေ့လာပါ။</Text></View>{authLoading ? <StateCard kind="loading" title="Session ကို စစ်နေပါတယ်" message="ခဏစောင့်ပေးပါ။" /> : !configured ? <StateCard kind="error" title="Supabase မချိတ်ရသေးပါ" message="Login အသုံးပြုရန် .env.local ထဲမှာ Supabase URL နဲ့ anon key ထည့်ပါ။" /> : <><View style={styles.form}><Text style={styles.label}>EMAIL</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="you@example.com" placeholderTextColor={colors.muted} style={styles.input} /><Text style={styles.label}>PASSWORD</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Password" placeholderTextColor={colors.muted} style={styles.input} />{error ? <Text style={styles.error}>{error}</Text> : null}</View><PrimaryButton label={busy ? 'ဝင်နေပါတယ်…' : 'အကောင့်ဝင်မယ်'} onPress={() => { void submit(); }} disabled={busy} /><View style={styles.switchRow}><Text style={styles.switchText}>အကောင့်မရှိသေးဘူးလား?</Text><Pressable onPress={() => router.replace('/register')}><Text style={styles.link}> Register လုပ်မယ်</Text></Pressable></View></>}</ScreenContainer>; }
const styles = StyleSheet.create({ back: { flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 22 }, backText: { color: colors.ink, fontSize: 12, fontWeight: '600' }, hero: { alignItems: 'center', paddingVertical: 28, borderRadius: radius.lg, backgroundColor: colors.primarySoft }, icon: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' }, title: { color: colors.ink, fontSize: 25, fontWeight: '800', marginTop: 13 }, subtitle: { color: colors.primary, fontSize: 11, marginTop: 5 }, form: { padding: 18, borderRadius: radius.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, marginVertical: 18 }, label: { color: colors.muted, fontSize: 9, letterSpacing: 1, fontWeight: '700', marginBottom: 7, marginTop: 4 }, input: { minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm, paddingHorizontal: 13, color: colors.ink, fontSize: 13, marginBottom: 14 }, error: { color: colors.error, fontSize: 11, lineHeight: 17 }, switchRow: { flexDirection: 'row', justifyContent: 'center', marginTop: 19 }, switchText: { color: colors.muted, fontSize: 11 }, link: { color: colors.primary, fontSize: 11, fontWeight: '800' }, });
