import { useRouter } from 'expo-router';
import { ArrowLeft, BookOpen, ChevronRight, CircleHelp, Headphones, Settings, Star, Target } from 'lucide-react-native';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ScreenContainer } from './screen-container';
import { PrimaryButton } from './ui';
import { colors, radius } from '../constants/theme';

const icons = { headphones: Headphones, quiz: CircleHelp, progress: Target, favorites: Star, settings: Settings, default: BookOpen } as const;
export function FoundationScreen({ title, subtitle, message, action, route, icon = 'default' }: { title: string; subtitle: string; message: string; action: string; route: '/(tabs)/vocab' | '/(tabs)/practice' | '/(tabs)' ; icon?: keyof typeof icons }) { const router = useRouter(); const Icon = icons[icon]; return <ScreenContainer><Pressable onPress={() => router.back()} style={styles.back}><ArrowLeft size={18} color={colors.ink} /><Text style={styles.backText}>ပြန်သွားမယ်</Text></Pressable><View style={styles.hero}><View style={styles.icon}><Icon size={23} color={colors.primary} /></View><Text style={styles.title}>{title}</Text><Text style={styles.subtitle}>{subtitle}</Text></View><View style={styles.message}><Text style={styles.messageTitle}>Foundation ready</Text><Text style={styles.messageText}>{message}</Text></View><PrimaryButton label={action} onPress={() => router.replace(route)} icon={ChevronRight} /></ScreenContainer>; }
const styles = StyleSheet.create({ back: { flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 24 }, backText: { color: colors.ink, fontSize: 12, fontWeight: '600' }, hero: { alignItems: 'center', paddingVertical: 35, borderRadius: radius.lg, backgroundColor: colors.primarySoft }, icon: { width: 50, height: 50, borderRadius: 25, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface }, title: { color: colors.ink, fontSize: 25, fontWeight: '800', marginTop: 15 }, subtitle: { color: colors.primary, fontSize: 12, marginTop: 5 }, message: { padding: 20, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, marginVertical: 18 }, messageTitle: { color: colors.ink, fontSize: 15, fontWeight: '800' }, messageText: { color: colors.muted, fontSize: 12, lineHeight: 20, marginTop: 8 }, });
