import { demoGrammar } from '../data/demo';
import type { GrammarItem, HskLevel } from '../data/types';
import { supabase, supabaseConfigured } from './supabase';

type GrammarRow = { id: string; title_zh: string; title_en: string; title_my: string; short_label_my: string; meaning_my: string; pattern: string; when_to_use_my: string; common_mistakes_my: string; hsk_min: number; hsk_max: number; grammar_examples?: Array<{ sentence_zh: string; sentence_pinyin: string; translation_my: string; translation_en?: string; sort_order: number }> };

const fallbackDetails: Record<string, Omit<GrammarItem, 'id'>> = {
  le: { titleZh: '了', titleEn: 'Completion and change', titleMy: 'ပြီးဆုံးမှု / အခြေအနေပြောင်းလဲမှု', shortLabelMy: 'လုပ်ပြီးပြီလို့ ပြောခြင်း', meaningMy: 'လုပ်ဆောင်ချက်ပြီးဆုံးသွားတာ သို့မဟုတ် အခြေအနေအသစ်ဖြစ်လာတာကို ပြောရန်။', pattern: 'Subject + Verb + 了 + Object', whenToUseMy: 'ပြီးဆုံးသွားတဲ့ action သို့မဟုတ် ပြောင်းလဲလာတဲ့အခြေအနေကို ပြောတဲ့အခါ သုံးပါတယ်။', commonMistakesMy: '了 ကို အတိတ်ကာလပြတိုင်း ထည့်ရမယ်လို့ မယူဆပါနဲ့။ Context အလိုက် အသုံးပြုရပါတယ်။', hskMin: 1, hskMax: 1, examples: [{ sentenceZh: '我吃饭了。', sentencePinyin: 'Wǒ chīfàn le.', translationMy: 'ငါ ထမင်းစားပြီးပြီ။', translationEn: 'I have eaten.' }, { sentenceZh: '下雨了。', sentencePinyin: 'Xiàyǔ le.', translationMy: 'မိုးရွာလာပြီ။', translationEn: 'It has started raining.' }] },
  guo: { titleZh: '过', titleEn: 'Past experience', titleMy: 'အတွေ့အကြုံ', shortLabelMy: 'ကြုံဖူးကြောင်း ပြောခြင်း', meaningMy: 'အတိတ်မှာ တစ်စုံတစ်ရာ ကြုံဖူးကြောင်း ပြောရန်။', pattern: 'Subject + Verb + 过 + Object', whenToUseMy: 'ဘဝအတွေ့အကြုံ သို့မဟုတ် တစ်ခုခု လုပ်ဖူးကြောင်း ပြောတဲ့အခါ သုံးပါတယ်။', commonMistakesMy: 'တိကျတဲ့ အတိတ်အချိန်နဲ့ တွဲသုံးတာထက် အတွေ့အကြုံကို အလေးပေးတဲ့အခါ သုံးပါ။', hskMin: 2, hskMax: 2, examples: [{ sentenceZh: '我去过中国。', sentencePinyin: 'Wǒ qù guo Zhōngguó.', translationMy: 'ငါ တရုတ်နိုင်ငံကို သွားဖူးတယ်။', translationEn: 'I have been to China.' }, { sentenceZh: '你吃过这个菜吗？', sentencePinyin: 'Nǐ chī guo zhège cài ma?', translationMy: 'ဒီဟင်းကို မင်းစားဖူးလား။', translationEn: 'Have you eaten this dish?' }] },
  ba: { titleZh: '把', titleEn: 'Object-focused construction', titleMy: 'အရာဝတ္ထုကို အလေးပေးခြင်း', shortLabelMy: 'Object ပေါ် အာရုံစိုက်ခြင်း', meaningMy: 'လုပ်ဆောင်ချက်ရဲ့ အကျိုးသက်ရောက်မှုကို object ပေါ် အလေးပေးရန်။', pattern: 'Subject + 把 + Object + Verb + Result', whenToUseMy: 'Object ကို ဘာလုပ်လိုက်သလဲ၊ ဘယ်လိုပြောင်းလဲသွားသလဲကို အလေးပေးချင်တဲ့အခါ သုံးပါတယ်။', commonMistakesMy: '把 နောက်မှာ object ထားပြီး verb မှာ result သို့မဟုတ် အခြား complement ပါရမယ်။', hskMin: 3, hskMax: 3, examples: [{ sentenceZh: '请把门关上。', sentencePinyin: 'Qǐng bǎ mén guān shàng.', translationMy: 'ကျေးဇူးပြုပြီး တံခါးပိတ်ပေးပါ။', translationEn: 'Please close the door.' }, { sentenceZh: '我把书放在桌子上。', sentencePinyin: 'Wǒ bǎ shū fàng zài zhuōzi shàng.', translationMy: 'ငါ စာအုပ်ကို စားပွဲပေါ် တင်ထားတယ်။', translationEn: 'I put the book on the table.' }] },
};

function mapGrammar(row: GrammarRow): GrammarItem { return { id: row.id, titleZh: row.title_zh, titleEn: row.title_en, titleMy: row.title_my, shortLabelMy: row.short_label_my, meaningMy: row.meaning_my, pattern: row.pattern, whenToUseMy: row.when_to_use_my, commonMistakesMy: row.common_mistakes_my, hskMin: row.hsk_min as HskLevel, hskMax: row.hsk_max as HskLevel, examples: (row.grammar_examples ?? []).sort((a, b) => a.sort_order - b.sort_order).map(example => ({ sentenceZh: example.sentence_zh, sentencePinyin: example.sentence_pinyin, translationMy: example.translation_my, translationEn: example.translation_en })), }; }

export async function getPublishedGrammar(): Promise<GrammarItem[]> { if (!supabaseConfigured) return demoGrammar.map(item => ({ id: item.id, ...fallbackDetails[item.id] })); const { data, error } = await supabase.from('grammar_lessons').select('id, title_zh, title_en, title_my, short_label_my, meaning_my, pattern, when_to_use_my, common_mistakes_my, hsk_min, hsk_max, grammar_examples(sentence_zh, sentence_pinyin, translation_my, translation_en, sort_order)').eq('status', 'published').order('sort_order').limit(100); if (error) throw error; return ((data ?? []) as unknown as GrammarRow[]).map(mapGrammar); }

export async function getPublishedGrammarDetail(id: string): Promise<GrammarItem> { if (!supabaseConfigured) { const preview = demoGrammar.find(item => item.id === id); if (!preview || !fallbackDetails[id]) throw new Error('Grammar lesson not found'); return { id: preview.id, ...fallbackDetails[id] }; } const { data, error } = await supabase.from('grammar_lessons').select('id, title_zh, title_en, title_my, short_label_my, meaning_my, pattern, when_to_use_my, common_mistakes_my, hsk_min, hsk_max, grammar_examples(sentence_zh, sentence_pinyin, translation_my, translation_en, sort_order)').eq('id', id).eq('status', 'published').maybeSingle(); if (error) throw error; if (!data) throw new Error('Grammar lesson not found'); return mapGrammar(data as unknown as GrammarRow); }
