import { supabase, supabaseConfigured } from './supabase';

type ContentType = 'vocabulary' | 'grammar' | 'quiz';
export type ProgressSummary = { vocabulary: { completed: number; total: number }; grammar: { completed: number; total: number }; quizzes: { completed: number; averageScore: number; attempts: number } };

/** The RPC derives ownership from auth.uid(); userId is retained only to avoid
 * recording when the current session is not the expected authenticated user. */
export async function recordLearningProgress(userId: string, contentType: ContentType, targetId: string, scorePercent?: number) { if (!supabaseConfigured) return; const { data: session } = await supabase.auth.getSession(); if (session.session?.user.id !== userId) return; const { error } = await supabase.rpc('record_learning_progress', { p_content_type: contentType, p_target_id: targetId, p_score_percent: scorePercent ?? null }); if (error) throw error; }

export async function getProgressSummary(userId: string): Promise<ProgressSummary> { if (!supabaseConfigured) return { vocabulary: { completed: 0, total: 0 }, grammar: { completed: 0, total: 0 }, quizzes: { completed: 0, averageScore: 0, attempts: 0 } }; const { data: session } = await supabase.auth.getSession(); if (session.session?.user.id !== userId) throw new Error('Authenticated user mismatch'); const { data, error } = await supabase.from('learning_progress').select('content_type, status, score_percent').eq('user_id', userId); if (error) throw error; const rows = data ?? []; const vocabulary = rows.filter(row => row.content_type === 'vocabulary'); const grammar = rows.filter(row => row.content_type === 'grammar'); const quizzes = rows.filter(row => row.content_type === 'quiz'); const scores = quizzes.map(row => Number(row.score_percent)).filter(score => Number.isFinite(score)); return { vocabulary: { completed: vocabulary.filter(row => row.status === 'completed' || row.status === 'started').length, total: vocabulary.length }, grammar: { completed: grammar.filter(row => row.status === 'completed' || row.status === 'started').length, total: grammar.length }, quizzes: { completed: quizzes.filter(row => row.status === 'completed').length, averageScore: scores.length ? Math.round(scores.reduce((sum, score) => sum + score, 0) / scores.length) : 0, attempts: quizzes.length } }; }
