import { demoQuizzes } from '../data/demo';
import type { HskLevel, QuizItem, QuizQuestion } from '../data/types';
import { supabase, supabaseConfigured } from './supabase';

type QuizRow = { id: string; title_my: string; title_en: string; description_my?: string | null; hsk_level_id?: number | null; quiz_type: string; status: string; quiz_questions?: Array<{ id: string; question_type: QuizQuestion['type']; prompt_zh?: string | null; prompt_pinyin?: string | null; prompt_my: string; explanation_my: string; points: number; sort_order: number; payload_json?: QuizQuestion['payload']; quiz_options?: Array<{ id: string; option_key: string; option_zh?: string | null; option_pinyin?: string | null; option_my?: string | null; is_correct: boolean; sort_order: number }>; quiz_question_answers?: Array<{ answer_display: string; answer_normalized: string; sort_order?: number }> }> };

const fallbackQuestions: QuizQuestion[] = [
  { id: 'demo-q1', type: 'multiple_choice', promptZh: '你好吗？', promptPinyin: 'Nǐ hǎo ma?', promptMy: 'အဓိပ္ပာယ်မှန်ကို ရွေးပါ။', explanationMy: '你好 က “မင်္ဂလာပါ” လို့ အဓိပ္ပာယ်ရပါတယ်။', points: 1, sortOrder: 1, options: [{ id: 'q1-a', key: 'A', optionMy: 'မင်္ဂလာပါ', isCorrect: true }, { id: 'q1-b', key: 'B', optionMy: 'ကျေးဇူးတင်ပါတယ်', isCorrect: false }, { id: 'q1-c', key: 'C', optionMy: 'သွားမယ်', isCorrect: false }] , acceptedAnswers: [] },
  { id: 'demo-q2', type: 'fill_blank', promptZh: '我每天____中文。', promptPinyin: 'Wǒ měitiān ____ Zhōngwén.', promptMy: 'နေရာလွတ်မှာ သင့်တော်တဲ့ စကားလုံးဖြည့်ပါ။', explanationMy: '学习 (xuéxí) က စာလေ့လာသည်လို့ အဓိပ္ပာယ်ရပါတယ်။', points: 1, sortOrder: 2, options: [], acceptedAnswers: ['学习', 'xuexi'] },
  { id: 'demo-q3', type: 'matching', promptMy: 'တရုတ်စကားနဲ့ မြန်မာအဓိပ္ပာယ်ကို တွဲပါ။', explanationMy: '你好 က မင်္ဂလာပါ၊ 谢谢 က ကျေးဇူးတင်ပါတယ် ဖြစ်ပါတယ်။', points: 1, sortOrder: 3, options: [], acceptedAnswers: [], payload: { pairs: [{ left: '你好', right: 'မင်္ဂလာပါ' }, { left: '谢谢', right: 'ကျေးဇူးတင်ပါတယ်' }] } },
  { id: 'demo-q4', type: 'sentence_ordering', promptMy: 'စကားလုံးတွေကို မှန်ကန်တဲ့ ဝါကျဖြစ်အောင် စီပါ။', explanationMy: 'တရုတ်ဝါကျမှာ subject နောက်မှာ time phrase နဲ့ verb phrase လာပါတယ်။', points: 1, sortOrder: 4, options: [], acceptedAnswers: [], payload: { tokens: ['我', '每天', '学习', '中文。'], answer: ['我', '每天', '学习', '中文。'] } },
];

const fallbackQuiz = (id: string, titleMy: string, titleEn: string, hskLevel: HskLevel): QuizItem => ({ id, titleMy, titleEn, descriptionMy: 'မေးခွန်းအမျိုးအစား အမျိုးမျိုးနဲ့ လေ့ကျင့်ပါ။', quizType: 'mixed', hskLevel, questionCount: fallbackQuestions.length, questions: fallbackQuestions });

function mapQuiz(row: QuizRow, includeQuestions: boolean): QuizItem { const questions = includeQuestions ? (row.quiz_questions ?? []).sort((a, b) => a.sort_order - b.sort_order).map(question => ({ id: question.id, type: question.question_type, promptZh: question.prompt_zh ?? undefined, promptPinyin: question.prompt_pinyin ?? undefined, promptMy: question.prompt_my, explanationMy: question.explanation_my, points: question.points, sortOrder: question.sort_order, options: (question.quiz_options ?? []).sort((a, b) => a.sort_order - b.sort_order).map(option => ({ id: option.id, key: option.option_key, optionZh: option.option_zh ?? undefined, optionPinyin: option.option_pinyin ?? undefined, optionMy: option.option_my ?? undefined, isCorrect: option.is_correct })), acceptedAnswers: (question.quiz_question_answers ?? []).map(answer => answer.answer_normalized), payload: question.payload_json } as QuizQuestion)) : []; return { id: row.id, titleMy: row.title_my, titleEn: row.title_en, descriptionMy: row.description_my ?? undefined, quizType: row.quiz_type, hskLevel: row.hsk_level_id ? row.hsk_level_id as HskLevel : undefined, questionCount: questions.length, questions }; }

export async function getPublishedQuizzes(): Promise<QuizItem[]> { if (!supabaseConfigured) return demoQuizzes.map(item => fallbackQuiz(item.id, item.titleMy, item.titleMy, item.hsk)); const { data, error } = await supabase.from('quizzes').select('id, title_my, title_en, description_my, hsk_level_id, quiz_type, status').eq('status', 'published').order('sort_order').limit(100); if (error) throw error; return ((data ?? []) as unknown as QuizRow[]).map(row => mapQuiz(row, false)); }

export async function getPublishedQuizDetail(id: string): Promise<QuizItem> { if (!supabaseConfigured) { const quiz = demoQuizzes.find(item => item.id === id); if (!quiz) throw new Error('Quiz not found'); return fallbackQuiz(quiz.id, quiz.titleMy, quiz.titleMy, quiz.hsk); } const { data, error } = await supabase.from('quizzes').select('id, title_my, title_en, description_my, hsk_level_id, quiz_type, status, quiz_questions(id, question_type, prompt_zh, prompt_pinyin, prompt_my, explanation_my, points, sort_order, payload_json, quiz_options(id, option_key, option_zh, option_pinyin, option_my, is_correct, sort_order), quiz_question_answers(answer_display, answer_normalized, sort_order))').eq('id', id).eq('status', 'published').maybeSingle(); if (error) throw error; if (!data) throw new Error('Quiz not found'); return mapQuiz(data as unknown as QuizRow, true); }
