import { demoSpeaking } from '../data/demo';
import type { HskLevel, SpeakingItem } from '../data/types';
import { supabase, supabaseConfigured } from './supabase';

type SpeakingRow = { id: string; title_my: string; title_en: string; title_zh?: string | null; description_my: string; scenario_type: string; hsk_level_id?: number | null; category_id?: string | null; dialogue_lines?: Array<{ id: string; speaker_key: string; speaker_label_my?: string | null; sentence_zh: string; sentence_pinyin: string; translation_my: string; sort_order: number }> };

const fallbackLines: Record<string, SpeakingItem['lines']> = {
  greeting: [{ id: 'greeting-1', speakerKey: 'A', speakerLabelMy: 'A', sentenceZh: '你好！', sentencePinyin: 'Nǐ hǎo!', translationMy: 'မင်္ဂလာပါ။', sortOrder: 1 }, { id: 'greeting-2', speakerKey: 'B', speakerLabelMy: 'B', sentenceZh: '你好！你好吗？', sentencePinyin: 'Nǐ hǎo! Nǐ hǎo ma?', translationMy: 'မင်္ဂလာပါ။ နေကောင်းလား။', sortOrder: 2 }],
  intro: [{ id: 'intro-1', speakerKey: 'A', speakerLabelMy: 'A', sentenceZh: '我叫 Shine。', sentencePinyin: 'Wǒ jiào Shine.', translationMy: 'ကျွန်တော့်နာမည် Shine ပါ။', sortOrder: 1 }, { id: 'intro-2', speakerKey: 'B', speakerLabelMy: 'B', sentenceZh: '认识你很高兴。', sentencePinyin: 'Rènshi nǐ hěn gāoxìng.', translationMy: 'တွေ့ရတာ ဝမ်းသာပါတယ်။', sortOrder: 2 }],
  shopping: [{ id: 'shopping-1', speakerKey: 'A', speakerLabelMy: 'A', sentenceZh: '这个多少钱？', sentencePinyin: 'Zhège duōshao qián?', translationMy: 'ဒါ ဘယ်လောက်လဲ။', sortOrder: 1 }, { id: 'shopping-2', speakerKey: 'B', speakerLabelMy: 'B', sentenceZh: '二十块钱。', sentencePinyin: 'Èrshí kuài qián.', translationMy: 'ယွမ် ၂၀ ပါ။', sortOrder: 2 }],
};

function mapSpeaking(row: SpeakingRow): SpeakingItem { return { id: row.id, titleMy: row.title_my, titleEn: row.title_en, titleZh: row.title_zh ?? undefined, descriptionMy: row.description_my, scenarioType: row.scenario_type, hskLevel: row.hsk_level_id ? row.hsk_level_id as HskLevel : undefined, lines: (row.dialogue_lines ?? []).sort((a, b) => a.sort_order - b.sort_order).map(line => ({ id: line.id, speakerKey: line.speaker_key, speakerLabelMy: line.speaker_label_my ?? undefined, sentenceZh: line.sentence_zh, sentencePinyin: line.sentence_pinyin, translationMy: line.translation_my, sortOrder: line.sort_order })), }; }

export async function getPublishedSpeaking(): Promise<SpeakingItem[]> { if (!supabaseConfigured) return demoSpeaking.map(item => ({ id: item.id, titleMy: item.titleMy, titleEn: item.titleMy, titleZh: item.titleZh, descriptionMy: item.descriptionMy, scenarioType: item.id, hskLevel: item.hsk, lines: fallbackLines[item.id] ?? [] })); const { data, error } = await supabase.from('speaking_lessons').select('id, title_my, title_en, title_zh, description_my, scenario_type, hsk_level_id, category_id, dialogue_lines(id, speaker_key, speaker_label_my, sentence_zh, sentence_pinyin, translation_my, sort_order)').eq('status', 'published').order('sort_order').limit(100); if (error) throw error; return ((data ?? []) as unknown as SpeakingRow[]).map(mapSpeaking); }

export async function getPublishedSpeakingDetail(id: string): Promise<SpeakingItem> { if (!supabaseConfigured) { const item = demoSpeaking.find(speaking => speaking.id === id); if (!item) throw new Error('Speaking lesson not found'); return { id: item.id, titleMy: item.titleMy, titleEn: item.titleMy, titleZh: item.titleZh, descriptionMy: item.descriptionMy, scenarioType: item.id, hskLevel: item.hsk, lines: fallbackLines[item.id] ?? [] }; } const { data, error } = await supabase.from('speaking_lessons').select('id, title_my, title_en, title_zh, description_my, scenario_type, hsk_level_id, category_id, dialogue_lines(id, speaker_key, speaker_label_my, sentence_zh, sentence_pinyin, translation_my, sort_order)').eq('id', id).eq('status', 'published').maybeSingle(); if (error) throw error; if (!data) throw new Error('Speaking lesson not found'); return mapSpeaking(data as unknown as SpeakingRow); }
