import { useCallback, useEffect, useState } from 'react';
import { useRouter } from 'expo-router';
import { Headphones, ListChecks, Play, Trophy } from 'lucide-react-native';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ScreenContainer } from '../../components/screen-container';
import { LessonCard, OfflineBanner, ScreenHeader, StateCard } from '../../components/ui';
import { colors, radius, shadow } from '../../constants/theme';
import type { QuizItem } from '../../data/types';
import { supabaseConfigured } from '../../lib/supabase';
import { getPublishedQuizzes } from '../../lib/quiz';

export default function PracticeScreen() { const router = useRouter(); const [quizzes, setQuizzes] = useState<QuizItem[]>([]); const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading'); const loadQuizzes = useCallback(async () => { setStatus('loading'); try { setQuizzes(await getPublishedQuizzes()); setStatus('ready'); } catch { setQuizzes([]); setStatus('error'); } }, []); useEffect(() => { void loadQuizzes(); }, [loadQuizzes]); return <ScreenContainer><ScreenHeader title="လေ့ကျင့်ခန်း" subtitle="လေ့လာထားတာတွေကို လေ့ကျင့်ပြီး ခိုင်မာအောင်လုပ်ပါ။" action="Profile" onAction={() => router.push('/profile')} />{!supabaseConfigured ? <OfflineBanner /> : null}<View style={styles.scoreCard}><View><Text style={styles.scoreKicker}>ဒီအပတ်ရဲ့ လေ့ကျင့်မှု</Text><Text style={styles.scoreTitle}>ဆက်လက်ကြိုးစားနေပါတယ်</Text><Text style={styles.scoreSub}>Quiz score ကို ဒီ session ထဲမှာသာ သိမ်းထားပါတယ်</Text></View><View style={styles.trophy}><Trophy size={22} color={colors.gold} /></View></View><Text style={styles.sectionLabel}>လေ့ကျင့်ရန် ရွေးချယ်ပါ</Text><Pressable onPress={() => router.push('/listening')} style={({ pressed }) => [styles.bigPractice, styles.listenBg, pressed && styles.pressed]}><View><View style={styles.iconCircle}><Headphones size={19} color={colors.primary} /></View><Text style={styles.bigTitle}>Listening practice</Text><Text style={styles.bigText}>နားထောင်ပြီး အဓိပ္ပာယ်နားလည်အောင် လေ့ကျင့်ပါ။</Text></View><Play size={22} color={colors.primary} /></Pressable><Pressable onPress={() => router.push('/quiz')} style={({ pressed }) => [styles.bigPractice, styles.quizBg, pressed && styles.pressed]}><View><View style={[styles.iconCircle, { backgroundColor: colors.white }]}><ListChecks size={19} color={colors.accent} /></View><Text style={styles.bigTitle}>Quiz ဖြေမယ်</Text><Text style={styles.bigText}>Vocabulary နဲ့ Grammar သိထားတာကို စမ်းသပ်ပါ။</Text></View><Play size={22} color={colors.accent} /></Pressable><View style={styles.quizHeader}><Text style={styles.sectionLabel}>Published Quiz collections</Text><Pressable onPress={() => router.push('/quiz')}><Text style={styles.seeAll}>အားလုံး →</Text></Pressable></View>{status === 'loading' ? <StateCard kind="loading" title="Quiz များကို ဖတ်နေပါတယ်" message="Published quiz content ကို ပြင်ဆင်နေပါတယ်။" /> : status === 'error' ? <StateCard kind="error" title="Quiz မဖွင့်နိုင်သေးပါ" message="Supabase connection သို့မဟုတ် content ကို စစ်ပါ။" action="ပြန်စမ်းမယ်" onAction={() => { void loadQuizzes(); }} /> : quizzes.length === 0 ? <StateCard kind="empty" title="Quiz မရှိသေးပါ" message="Published quiz content ထည့်ပြီးနောက် ဒီနေရာမှာ ပြပါမယ်။" /> : quizzes.slice(0, 3).map(quiz => <LessonCard key={quiz.id} titleZh={quiz.hskLevel ? `HSK ${quiz.hskLevel}` : 'Quiz'} titleMy={quiz.titleMy} meta={`${quiz.quizType} · မေးခွန်း ${quiz.questionCount} ခု`} icon={ListChecks} onPress={() => router.push({ pathname: '/quiz/[id]', params: { id: quiz.id } })} />)}</ScreenContainer>; }
const styles = StyleSheet.create({ scoreCard: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 18, borderRadius: radius.md, backgroundColor: colors.ink, marginBottom: 28 }, scoreKicker: { color: '#A5CFC6', fontSize: 10, letterSpacing: 1, fontWeight: '700' }, scoreTitle: { color: colors.white, fontSize: 16, fontWeight: '800', marginTop: 8 }, scoreSub: { color: '#B8C4C1', fontSize: 10, marginTop: 5 }, trophy: { width: 48, height: 48, borderRadius: 24, backgroundColor: '#394440', alignItems: 'center', justifyContent: 'center' }, sectionLabel: { color: colors.muted, fontSize: 10, fontWeight: '700', marginBottom: 11 }, bigPractice: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 18, borderRadius: radius.md, marginBottom: 10, ...shadow.card }, listenBg: { backgroundColor: colors.primarySoft }, quizBg: { backgroundColor: colors.accentSoft }, pressed: { opacity: .86 }, iconCircle: { width: 37, height: 37, borderRadius: 19, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', marginBottom: 13 }, bigTitle: { color: colors.ink, fontSize: 15, fontWeight: '800' }, bigText: { color: colors.muted, fontSize: 10, lineHeight: 16, marginTop: 5, maxWidth: 250 }, quizHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 21 }, seeAll: { color: colors.primary, fontSize: 10, fontWeight: '700' }, });
